POST http://localhost:8080/registerParty HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "firstName": "Tom", "lastName": "Huber", "partyName":"tom", "location":"toms home", "date":"21.12.2018" }
###
POST http://localhost:8080/registerParty HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "firstName": "Franz", "lastName": "Müller", "partyName":"franz", "location":"franzs home", "date":"19.12.2018" }
###
POST http://localhost:8080/register/tom HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "firstName": "Tsd", "lastName": "sdfBar" }
###

POST http://localhost:8080/register/franz HTTP/1.1
Accept: application/json
Content-Type: application/json

{ "firstName": "Tsd", "lastName": "sdfBar" }
###
GET http://localhost:8080/guests/tom HTTP/1.1
Accept: application/json

###
GET http://localhost:8080/guests/tom HTTP/1.1
Accept: application/json
Authorization: Basic admin:admin

###
GET http://localhost:8080/guests/tom HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46UEBzc3cwcmQh

###
GET http://localhost:8080/guests HTTP/1.1
Accept: application/json

###
GET http://localhost:8080/party/tom HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46UEBzc3cwcmQh

### 
GET http://localhost:8080/party/franz HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46UEBzc3cwcmQh

### 
GET http://localhost:8080/party/tom HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46UEBzc3cwcmQh